name: iOS Deploy

on:
  workflow_dispatch:
    inputs:
      lane:
        description: 'Which lane to run?'
        required: true
        default: 'upload'
        type: choice
        options:
          - upload
          - release

jobs:
  deploy:
    runs-on: self-hosted  # Aapka apna Mac use hoga

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Fastlane
        env:
          APP_STORE_KEY_ID: ${{ secrets.APP_STORE_KEY_ID }}
          APP_STORE_ISSUER_ID: ${{ secrets.APP_STORE_ISSUER_ID }}
          APP_STORE_KEY_CONTENT: ${{ secrets.APP_STORE_KEY_CONTENT }}
          APP_IDENTIFIER: ${{ secrets.APP_IDENTIFIER }}
          APPLE_ID: ${{ secrets.APPLE_ID }}
          TEAM_ID: ${{ secrets.TEAM_ID }}
        run: fastlane ${{ github.event.inputs.lane }}
